#!/usr/bin/env node
"use strict";

// Writes `src/version.generated.ts` from this package's own `version`.
//
// The plugin reports its version in its handshake, and core prints that when a
// protocol mismatch refuses the load. It used to be a hand-maintained constant
// under a comment asking whoever touched it to keep it in step with
// package.json; nobody did, so the wire said 0.1.0 for three releases while
// `g-mesh plugins list` said 2.1.0 about the same plugin. One declaration
// cannot drift from itself.
//
// Runs as `prebuild`, so both build paths get it for free: core's build.rs and
// scripts/bundle-plugin.sh each run `npm run build`.

const fs = require("node:fs");
const path = require("node:path");

const pluginDir = path.resolve(__dirname, "..");
const { version } = require(path.join(pluginDir, "package.json"));

if (typeof version !== "string" || version.length === 0) {
  console.error("generate-version: package.json declares no version");
  process.exit(1);
}

const target = path.join(pluginDir, "src", "version.generated.ts");
const contents = `// Generated by scripts/generate-version.js from package.json's "version".
// Do not edit, and do not commit: \`npm run build\` writes it.
export const PLUGIN_VERSION = ${JSON.stringify(version)};
`;

// Only when it would actually change. core/build.rs declares
// `rerun-if-changed` on this directory, so an unconditional write would give
// the file a fresh mtime on every build and leave each `cargo build` dirtying
// the next one.
let existing = null;
try {
  existing = fs.readFileSync(target, "utf8");
} catch (err) {
  if (err.code !== "ENOENT") {
    throw err;
  }
}

if (existing !== contents) {
  fs.writeFileSync(target, contents);
}
